package de.wohlers.fluxerrorreporter.model.dtos;

import lombok.Getter;
import lombok.Setter;

import java.net.URI;

@Getter
@Setter
public class ProblemDTO {
    /**
     * A URI reference that uniquely identifies the problem type only in the
     * context of the provided API. Opposed to the specification in RFC-7807,
     * it is neither recommended to be dereference-able and point to a
     * human-readable documentation nor globally unique for the problem type.
     */
    private URI type;
    /**
     * A short summary of the problem type. Written in English and readable
     * for engineers, usually not suited for non-technical stakeholders and
     * not localized.
     */
    private String title;
    /**
     * The HTTP status code generated by the origin server for this occurrence
     * of the problem.
     */
    private Integer status;
    /**
     * A human-readable explanation specific to this occurrence of the
     * problem that is helpful to locate the problem and give advice on how
     * to proceed. Written in English and readable for engineers, usually not
     * suited for non-technical stakeholders and not localized.
     */
    private String detail;
    /**
     * A URI reference that identifies the specific occurrence of the problem,
     * e.g. by adding a fragment identifier or sub-path to the problem type.
     * May be used to locate the root of this problem in the source code.
     */
    private URI instance;
}
